name: Build and Deploy

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codebase

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install yarn package manager
      run: npm install -g yarn 
    - name: Install project dependencies
      run: yarn install
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.1.4
      with:
        name: drop
        path: ./codebase/*
  
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
        
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: drop
          path: ./codebase
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SFTP_USER }} 
          server: ${{ secrets.SFTP_SERVER }} 
          port: 22
          ssh_private_key: ${{ secrets.SFTP_KEY }} 
          local_path: ./codebase/*
          remote_path: /var/www/rpg-buddy